name:                todoshell
version:             0.1.0.0
github:              "githubuser/todoshell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todoshell#readme>

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- TupleSections
- LambdaCase
- RankNTypes

dependencies:
- classy-prelude
- base

library:
  source-dirs: src
  exposed-modules:
  - TodoShell
  dependencies:
  - base
  - brick
  - text
  - mtl
  - vty
  - containers

executables:
  todoshell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todoshell

tests:
  todoshell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todoshell
